name: cmcc-dr-cmip7
channels:
  - conda-forge
  - nodefaults
dependencies:
  - numpy
  - bs4
  - coverage
  - openpyxl
  - pooch
  - pytest
  - pyyaml
  - requests
  - pip
  # regular pip packages
  - pip:
    - CMIP7-data-request-api

